#!/usr/bin/env node

import { randomUUID } from "node:crypto";
import {
	access,
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	realpath,
	rename,
	rm,
	writeFile,
} from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDirectory = join(packageRoot, "dist");
const GENERATED_BANNER = [
	"// @generated by scripts/build-runtime.mjs; do not edit.",
	"// @ts-nocheck -- generated JavaScript uses a .ts extension for Pi's Jiti loader.",
].join("\n");
const FORBIDDEN_EAGER_INPUTS = ["src/account-menu.ts"];
const FORBIDDEN_EAGER_EXTERNALS = ["@narumitw/pi-tui-kit"];

export async function buildRuntime({
	outputDirectory = distDirectory,
	validateOutput = validateGeneratedFiles,
} = {}) {
	const resolvedOutputDirectory = resolve(outputDirectory);
	await assertSafeOutputDirectory(resolvedOutputDirectory);
	await mkdir(dirname(resolvedOutputDirectory), { recursive: true });
	const stagingDirectory = await mkdtemp(
		join(dirname(resolvedOutputDirectory), ".pi-accounts-dist-"),
	);

	try {
		const result = await build({
			absWorkingDir: packageRoot,
			banner: { js: GENERATED_BANNER },
			bundle: true,
			chunkNames: "chunks/[name]-[hash]",
			entryNames: "index",
			entryPoints: ["src/index.ts"],
			format: "esm",
			legalComments: "none",
			metafile: true,
			outdir: stagingDirectory,
			packages: "external",
			platform: "node",
			sourcemap: true,
			splitting: true,
			target: "es2022",
			write: true,
		});
		validateEagerGraph(result.metafile);
		await prepareGeneratedRuntime(stagingDirectory);
		await validateOutput(stagingDirectory);
		await publishRuntime(stagingDirectory, resolvedOutputDirectory);
		return result.metafile;
	} catch (error) {
		await rm(stagingDirectory, { force: true, recursive: true });
		throw error;
	}
}

export function validateEagerGraph(metadata) {
	const outputs = metadata.outputs ?? {};
	const entry = Object.entries(outputs).find(([, output]) =>
		normalizePath(output.entryPoint ?? "").endsWith("/src/index.ts"),
	);
	if (!entry) throw new Error("Generated runtime metadata has no src/index.ts entrypoint");

	for (const output of Object.values(outputs)) {
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			const normalized = normalizePath(inputPath);
			if (normalized.includes("/node_modules/")) {
				throw new Error(`Bundled package input: ${normalized}`);
			}
		}
	}

	const eagerOutputs = collectEagerOutputs(outputs, entry[0]);
	const eagerInputs = new Set();
	for (const outputPath of eagerOutputs) {
		const output = outputs[outputPath];
		if (!output) continue;
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			eagerInputs.add(normalizePath(inputPath));
		}
		for (const imported of output.imports ?? []) {
			if (
				imported.external &&
				imported.kind !== "dynamic-import" &&
				FORBIDDEN_EAGER_EXTERNALS.some(
					(dependency) =>
						imported.path === dependency || imported.path.startsWith(`${dependency}/`),
				)
			) {
				throw new Error(
					`Eager external dependency: ${imported.path} from ${normalizePath(outputPath)}`,
				);
			}
		}
	}

	for (const forbidden of FORBIDDEN_EAGER_INPUTS) {
		if ([...eagerInputs].some((input) => input.endsWith(`/${forbidden}`))) {
			throw new Error(`First-use implementation is eager: ${forbidden}`);
		}
	}
	return { eagerInputs, eagerOutputs };
}

export async function validateGeneratedFiles(outputDirectory) {
	const files = await listFiles(outputDirectory);
	const runtimeFiles = files.filter((path) => path.endsWith(".ts") || path.endsWith(".js"));
	if (files.some((path) => path.startsWith("chunks/") && path.endsWith(".ts"))) {
		throw new Error("Generated runtime retains a TypeScript chunk");
	}
	if (!runtimeFiles.includes("index.ts")) throw new Error("Generated runtime is missing index.ts");
	if (
		FORBIDDEN_EAGER_INPUTS.length > 0 &&
		!runtimeFiles.some((path) => path.startsWith("chunks/"))
	) {
		throw new Error("Generated runtime has no lazy chunks");
	}

	for (const runtimePath of runtimeFiles) {
		const source = await readFile(join(outputDirectory, runtimePath), "utf8");
		if (!source.startsWith(GENERATED_BANNER)) {
			throw new Error(`Generated marker is missing from ${runtimePath}`);
		}
		if (/["']\.\.?\/[^"']+\.ts["']/u.test(source)) {
			throw new Error(`Generated runtime retains a .ts import specifier in ${runtimePath}`);
		}
		if (/["']\.\.?\/[^"']*src\//u.test(source)) {
			throw new Error(`Generated runtime imports authoritative source from ${runtimePath}`);
		}
		for (const match of source.matchAll(/["'](\.\.?\/[^"']+\.js)["']/gu)) {
			const targetPath = join(dirname(runtimePath), match[1]).replaceAll("\\", "/");
			if (!files.includes(targetPath)) {
				throw new Error(`Generated runtime import is missing: ${runtimePath} -> ${match[1]}`);
			}
		}
		if (!files.includes(`${runtimePath}.map`)) {
			throw new Error(`Source map is missing for ${runtimePath}`);
		}
	}
}

async function assertSafeOutputDirectory(outputDirectory) {
	const relativeOutput = relative(packageRoot, outputDirectory);
	const firstSegment = relativeOutput.split(sep)[0];
	const isDefaultOutput = relativeOutput === "dist";
	const isTestOutput = firstSegment?.startsWith(".pi-accounts-build-test-");
	if (
		relativeOutput === "" ||
		relativeOutput === ".." ||
		relativeOutput.startsWith(`..${sep}`) ||
		isAbsolute(relativeOutput) ||
		(!isDefaultOutput && !isTestOutput)
	) {
		throw new Error(
			"Runtime output directory must be inside the package root and owned by the build",
		);
	}

	const realPackageRoot = await realpath(packageRoot);
	const realOutputParent = await realpath(dirname(outputDirectory));
	const relativeParent = relative(realPackageRoot, realOutputParent);
	if (
		relativeParent === ".." ||
		relativeParent.startsWith(`..${sep}`) ||
		isAbsolute(relativeParent)
	) {
		throw new Error("Runtime output parent must not escape the package root through a symlink");
	}
}

function collectEagerOutputs(outputs, entryPath) {
	const eager = new Set();
	const pending = [entryPath];
	while (pending.length > 0) {
		const outputPath = pending.pop();
		if (!outputPath || eager.has(outputPath)) continue;
		eager.add(outputPath);
		for (const imported of outputs[outputPath]?.imports ?? []) {
			if (imported.external || imported.kind === "dynamic-import") continue;
			if (outputs[imported.path]) pending.push(imported.path);
		}
	}
	return eager;
}

async function prepareGeneratedRuntime(outputDirectory) {
	const jsEntryPath = join(outputDirectory, "index.js");
	const tsEntryPath = join(outputDirectory, "index.ts");
	const jsMapPath = join(outputDirectory, "index.js.map");
	const tsMapPath = join(outputDirectory, "index.ts.map");
	const source = await readFile(jsEntryPath, "utf8");
	const rewritten = source.replace(
		"sourceMappingURL=index.js.map",
		"sourceMappingURL=index.ts.map",
	);
	if (rewritten === source) throw new Error("Generated entry source map reference is missing");
	await writeFile(jsEntryPath, rewritten, "utf8");
	await rename(jsMapPath, tsMapPath);
	await rename(jsEntryPath, tsEntryPath);
}

export async function publishRuntime(
	stagingDirectory,
	outputDirectory,
	{ renamePath = rename } = {},
) {
	const backupDirectory = `${outputDirectory}.backup-${randomUUID()}`;
	const hadPreviousOutput = await exists(outputDirectory);
	if (hadPreviousOutput) await renamePath(outputDirectory, backupDirectory);
	try {
		await renamePath(stagingDirectory, outputDirectory);
	} catch (error) {
		if (hadPreviousOutput) {
			await rm(outputDirectory, { force: true, recursive: true });
			await renamePath(backupDirectory, outputDirectory);
		}
		throw error;
	}
	if (hadPreviousOutput) await rm(backupDirectory, { force: true, recursive: true });
}

async function exists(path) {
	try {
		await access(path);
		return true;
	} catch {
		return false;
	}
}

async function listFiles(directory, prefix = "") {
	const files = [];
	for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
		const relativePath = join(prefix, entry.name);
		if (entry.isDirectory()) files.push(...(await listFiles(directory, relativePath)));
		else if (entry.isFile()) files.push(relativePath.replaceAll("\\", "/"));
	}
	return files.sort();
}

function normalizePath(path) {
	const normalized = path.replaceAll("\\", "/");
	if (!isAbsolute(path)) return `/${normalized.replace(/^\.\//u, "")}`;
	return `/${relative(packageRoot, path).replaceAll("\\", "/")}`;
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
